export const MINISTERIOS = [
  { value: "liderancaCo", label: "Liderança C.O" },
  { value: "coTeens", label: "Liderança C.O Teens" },
  { value: "voluntarioCo", label: "Voluntário C.O" },
  { value: "coMusic", label: "C.O Music" },
  { value: "outdoor", label: "Outdoor" },
  { value: "centralDance", label: "Central Dance" },
  { value: "somDaCentral", label: "Som da Central" },
  { value: "evangelismo", label: "Evangelismo" },
  { value: "diaconato", label: "Diaconato" },
  { value: "kids", label: "Kids" },
  { value: "libras", label: "Libras" },
  { value: "casaPaz", label: "Casa de Paz" },
  { value: "cenic", label: "Central Cenic" },
] as const;
